#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

# Float some windows rather than fixing them
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Things$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotify$" sticky=on layer=above manage=off
yabai -m rule --add app="^Slack$" sticky=on layer=above manage=off

# general space settings
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# Paddings
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

echo "yabai configuration loaded.."