#!/usr/bin/env sh

# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

# Float some windows rather than fixing them
yabai -m rule --add app="^System Settings$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Things$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Spotify$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Slack$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Discord$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Simulator$" sticky=on sub-layer=above manage=off
yabai -m rule --add app="^Raycast$" sticky=on sub-layer=above manage=off

# general space settings
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.50

# Paddings
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize